# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(620, 620)
        MainWindow.setMinimumSize(QtCore.QSize(620, 620))
        MainWindow.setMaximumSize(QtCore.QSize(620, 620))
        MainWindow.setStyleSheet("QWidget#centralwidget {\n"
"     background-image:url(:/background/images/back_pers.png)\n"
"    }")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_exit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_exit.setGeometry(QtCore.QRect(440, 570, 150, 35))
        self.pushButton_exit.setMinimumSize(QtCore.QSize(150, 35))
        self.pushButton_exit.setMaximumSize(QtCore.QSize(150, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        self.pushButton_exit.setFont(font)
        self.pushButton_exit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_exit.setStyleSheet("QPushButton {\n"
"    background-color: rgb(192, 165, 157);\n"
"    background-image: url(:/background/images/exit.png)\n"
" }\n"
"QPushButton:hover {\n"
"     background-color:rgb(255, 237, 221);\n"
" }")
        self.pushButton_exit.setText("")
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.label_account_name = QtWidgets.QLabel(self.centralwidget)
        self.label_account_name.setGeometry(QtCore.QRect(40, 100, 141, 27))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(True)
        self.label_account_name.setFont(font)
        self.label_account_name.setStyleSheet("color:rgb(66, 46, 41)")
        self.label_account_name.setText("")
        self.label_account_name.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_account_name.setObjectName("label_account_name")
        self.wins = QtWidgets.QLabel(self.centralwidget)
        self.wins.setGeometry(QtCore.QRect(120, 480, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        self.wins.setFont(font)
        self.wins.setStyleSheet("color:rgb(66, 46, 41)")
        self.wins.setText("")
        self.wins.setObjectName("wins")
        self.loses = QtWidgets.QLabel(self.centralwidget)
        self.loses.setGeometry(QtCore.QRect(170, 510, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        self.loses.setFont(font)
        self.loses.setStyleSheet("color:rgb(66, 46, 41)")
        self.loses.setText("")
        self.loses.setObjectName("loses")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(160, 130, 301, 281))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_new_game_ai = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_new_game_ai.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        self.pushButton_new_game_ai.setFont(font)
        self.pushButton_new_game_ai.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_new_game_ai.setStyleSheet("QPushButton {\n"
"    background-color: rgb(192, 165, 157);\n"
"    background-image: url(:/background/images/play_bot.png)\n"
" }\n"
"QPushButton:hover {\n"
"     background-color:rgb(255, 237, 221);\n"
" }")
        self.pushButton_new_game_ai.setText("")
        self.pushButton_new_game_ai.setObjectName("pushButton_new_game_ai")
        self.verticalLayout.addWidget(self.pushButton_new_game_ai)
        self.pushButton_new_game_friend = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_new_game_friend.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        self.pushButton_new_game_friend.setFont(font)
        self.pushButton_new_game_friend.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_new_game_friend.setStyleSheet("QPushButton {\n"
"    background-color: rgb(192, 165, 157);\n"
"    background-image: url(:/background/images/play_friend.png)\n"
" }\n"
"QPushButton:hover {\n"
"     background-color:rgb(255, 237, 221);\n"
" }")
        self.pushButton_new_game_friend.setText("")
        self.pushButton_new_game_friend.setObjectName("pushButton_new_game_friend")
        self.verticalLayout.addWidget(self.pushButton_new_game_friend)
        self.pushButton_old = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_old.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        self.pushButton_old.setFont(font)
        self.pushButton_old.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_old.setStyleSheet("QPushButton {\n"
"    background-color: rgb(192, 165, 157);\n"
"    background-image: url(:/background/images/play_recent.png)\n"
" }\n"
"QPushButton:hover {\n"
"     background-color:rgb(255, 237, 221);\n"
" }")
        self.pushButton_old.setText("")
        self.pushButton_old.setObjectName("pushButton_old")
        self.verticalLayout.addWidget(self.pushButton_old)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Личный кабинет"))
import back_reg


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
